# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoproduct',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 3, 22, 10, 29, 15, 310127, tzinfo=utc), upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
